export const GET_DESTINOS = 'GET_DESTINOS';
export const DESTINOS_ERROR = 'DESTINOS_ERROR';

export const QUERY_COTIZACION_SUCCESS = 'QUERY_COTIZACION_SUCCESS';
export const QUERY_COTIZACION_FAILURE = 'QUERY_COTIZACION_FAILURE';
export const QUERY_COTIZACION_STARTED = 'QUERY_COTIZACION_STARTED';
